const ADD_PROJECT = "ADD_PROJECT";
const EDIT_PROJECT = "EDIT_PROJECT";
const DELETE_PROJECT = "DELETE_PROJECT";
const NOTIFY = "NOTIFY";

export { ADD_PROJECT, EDIT_PROJECT, DELETE_PROJECT, NOTIFY };

