const GET_PROJECTS = "GET_PROJECTS";
const POST_PROJECT = "POST_PROJECT";
const PATCH_PROJECT = "PATCH_PROJECT";
const DELETE_PROJECT = "DELETE_PROJECT";

const POST_TASK = "POST_TASK";
const GET_TASKS = "GET_TASKS";
const PATCH_TASK = "PATCH_TASK";

export { GET_PROJECTS, POST_PROJECT, PATCH_PROJECT, DELETE_PROJECT, POST_TASK, GET_TASKS, PATCH_TASK };

