const ADD_PROJECT = "ADD_PROJECT";
const EDIT_PROJECT = "EDIT_PROJECT";
const DELETE_PROJECT = "DELETE_PROJECT";
const SET_PROJECTS = "SET_PROJECTS";

const NOTIFY = "NOTIFY";

const ADD_TASK = "ADD_TASK";
const SET_TASKS = "SET_TASKS";
const EDIT_TASK = "EDIT_TASK";

export { ADD_PROJECT, EDIT_PROJECT, DELETE_PROJECT, NOTIFY, SET_PROJECTS, ADD_TASK, SET_TASKS, EDIT_TASK };

